# Generated by Django 2.2.5 on 2021-02-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('borders', models.ManyToManyField(related_name='_country_borders_+', to='path_finder.Country')),
            ],
        ),
    ]
