# Generated by Django 3.1.7 on 2021-02-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='dist',
            field=models.IntegerField(null=True),
        ),
    ]
